### PR TITLE
Add repro for deadlock

### PR DESCRIPTION
**Pull request by lionello**
This PR adds a test to show the deadlock experienced by https://github.com/fabiospampinato/watcher/issues/8. The only way to make the test pass is to set `concurrency` to a value higher than the number of "folders".

### CODE REVIEW

**Comment by lionello** [comment]
Frankly, it's impossible to solve this in a consistent manner just because of the way tree-iteration works. If you want to be consistent so that iteration behaves the same with and without limiter, ie. a promise completes when its children have completed, you will always run into trouble when the "concurrency" limit is too small since any parent occupies one "count" until the children are done, etc.. `tiny-readdir` simply can't work with this limiter.

**Comment by fabiospampinato** [comment]
@lionello I'll look into this tomorrow. Do you have any suggestions? Obviously we can't get stuck forever, maybe we'll have to trade off the order in which operations happen for the assurance that they will complete? 🤔

**Comment by fabiospampinato** [comment]
Maybe the solution here is to just mention the potential for deadlocks in the readme, and not limit concurrency in tiny-readdir but instead just yield to the event loop every now and then, which is what I actually wanted in the first place 🤔

**Comment by fabiospampinato** [comment]
Yeah let me get this fixed in tiny-readdir.

**Comment by lionello** [comment]
> Maybe the solution here is to just mention the potential for deadlocks in the readme, and not limit concurrency in tiny-readdir but instead just yield to the event loop every now and then, which is what I actually wanted in the first place 🤔

This sounds right. Thanks for the fix!

**Pull request closed without merging**
